build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Alloy"
  org.opencontainers.image.description: "Alloy Addon."
  org.opencontainers.image.source: "https://github.com/ricveal/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.vendor: "ricveal"
args:
  ALLOY_VERSION: "v1.8.1"
