name: "Alloy"
description: "Send logs to Loki instance"
version: "0.3.0"
slug: "alloy"
init: false
arch:
  - amd64
  - aarch64
options:
  instance_name: homeassistant
  job_name: homeassistant
  loki_url: null
  loki_username: null
  loki_password: null
  log_level: info
schema:
  instance_name: str?
  job_name: str?
  loki_url: str
  loki_username: str
  loki_password: str
  log_level: list(debug|info|warn|error)
journald: true
image: "ghcr.io/ricveal/hass-addon-alloy-{arch}"
