name: "Alloy"
description: "Send metrics & logs to Loki instance"
version: "0.1.0"
slug: "alloy"
init: false
arch:
  - amd64
  - aarch64
options:
  instance_name: homeassistant
  job_name: homeassistant
  loki_url: null
  loki_username: null
  loki_password: null
  verify_loki_ssl: false
  log_level: info
schema:
  instance_name: str?
  job_name: str?
  loki_url: str
  loki_username: str
  loki_password: str
  verify_loki_ssl: bool?
  log_level: list(debug|info|warn|error)
homeassistant_api: true
map:
  - homeassistant_config
image: "ghcr.io/ricveal/hass-addon-alloy-{arch}"
